---
    apiVersion: skaffold/v2alpha3
    kind: Config
    deploy:
      kubectl:
        manifests:
          - ./infra/k8s/*.yaml
          - ./infra/k8s-dev/*.yaml
    build:
      local:
        push: false
      artifacts:
        - image: yeniere/test
          context: test
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
    