name: tests-test

on:
  pull_request:
    paths:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd test && npm install && npm run test:ci
